id = "b64cc71d-8594-4617-b3fb-3057fca0b56b"
created_at = "2026-07-25T22:33:57.743728200+00:00"
title = "session-api tool_metrics core"
state = "done"
component = "session"
risk_level = "medium"
type = "feature"
workflow_stage = "planning"
