id = "274c3fcf-1502-41b3-af5b-cd1e7e599e79"
created_at = "2026-08-05T13:49:34.482618700+00:00"
title = "Author shared feedback API specification"
state = "planning"
component = "feedback"
effort = "8000"
priority = "high"
type = "task"
