id = "65ea4528-af24-4300-8e5f-3b68e54711d0"
created_at = "2026-06-17T14:03:38.264849900+00:00"
title = "[architecture][contracts] Core shared contract crate"
state = "planning"
effort = "2200"
priority = "high"
type = "tracker-improvement"
component = "doc"
