id = "b566755e-84ca-5560-b4d3-03a960af9f87"
created_at = "2026-08-06T02:10:51.309438600+00:00"
title = "[feedback-followup][ticket] Address not-helpful feedback on ce://default/ticket/85012858-cbf3-40df-b55e-b82e89f72434"
state = "planning"
component = "ticket"
priority = "medium"
type = "tracker-improvement"
