id = "5e1e799e-860c-43f3-ac1a-598d29780b23"
created_at = "2026-08-06T00:21:27.883455200+00:00"
title = "Research catalog-driven client integration"
state = "planning"
depends_on = ["abd3f280-9bd1-48cf-8503-17dd820afb30"]
effort = "1500"
priority = "high"
target_schema_type = "research"
type = "tracker-improvement"
workflow_role = "research"
component = "log"
