id = "321f4ec7-03df-4e14-9734-a6af76ace55f"
created_at = "2026-04-18T15:00:07.873360400+00:00"
title = "[spec][P8] Bootstrap: write spec files for ticket-vscode interface"
state = "planning"
component = "spec"
depends_on = ["090b6db9-f88e-418b-888e-94641d347432"]
effort = "1200"
phase = "8"
priority = "low"
type = "tracker-improvement"
