id = "d0ccdb06-db44-464f-846e-9d58c1320fd0"
created_at = "2026-05-11T13:34:34.378752+00:00"
title = "Complete memory-api rule-api specs and test links"
state = "planning"
component = "rule"
effort = "1200"
priority = "high"
type = "tracker-improvement"
