id = "7fbe52b5-ab69-4b3c-adaa-21d42cf26de8"
created_at = "2026-07-05T19:02:59.349315+00:00"
title = "[audit-roadmap][file_length][batch-5] viewer-api (7)"
state = "planning"
depends_on = ["5f7b2051-e577-4655-a9f8-02d0ea8b588c"]
effort = "1200"
type = "tracker-improvement"
component = "audit"
