id = "89f21dd2-6307-4f30-b0f8-7b36b3cfce66"
created_at = "2026-06-17T16:04:20+00:00"
title = "[audit-api] Health score recompute and queue refresh SLOs"
state = "planning"
depends_on = ["67b6117b-5978-4c89-9cd4-4c8b043f4fba"]
effort = "430"
priority = "high"
type = "tracker-improvement"
component = "audit"
