id = "74424d6f-327d-4de3-8dd2-3f26962c171d"
created_at = "2026-04-30T12:41:43.441861800+00:00"
title = "[spec-viewer][P5.4] Theme settings in Modal overlay"
state = "done"
type = "tracker-improvement"
component = "spec"
