id = "b6b58573-01c6-43c0-b8de-59c9c2afbe3f"
created_at = "2026-08-05T13:49:01.948102800+00:00"
title = "Define default output and transport negotiation for spec 1d62442b"
state = "planning"
component = "ticket"
effort = "4000"
priority = "high"
type = "task"
