id = "86bf3da2-b6cc-4fc7-898d-044403283550"
created_at = "2026-06-02T15:26:27.492343300+00:00"
title = "[test-api] Bootstrap validation specification and execution identities for spec fulfillment"
state = "done"
depends_on = ["c73d4a6b-2610-4e69-9fc3-bfedcf2ec53d"]
effort = "2600"
type = "tracker-improvement"
component = "audit"
