id = "fcced2f3-c32c-4533-9743-56543f428222"
created_at = "2026-05-18T22:25:58.783015300+00:00"
title = "[ticket-viewer][ticket-http] Search syntax hints and pattern contract"
state = "done"
component = "ticket"
priority = "high"
tags = "ticket-viewer,ticket-http,ticket-api,search,syntax,docs"
type = "tracker-improvement"
