id = "40da867e-4ccb-496c-bfda-f8e9d26db75c"
created_at = "2026-08-05T13:49:05.687474300+00:00"
title = "Define symlink confinement for spec 58a1d32c"
state = "planning"
component = "audit"
effort = "4000"
priority = "high"
type = "task"
