id = "38a8ea3a-9a6a-4a0f-bc5a-97dc9ba670fc"
created_at = "2026-10-01T00:39:09.005970400+00:00"
title = "Mission Domain"
state = "draft"
component = "mission"
scope = "internal"
slug = "workflow-tools/mission-domain"
type = "specification"
