id = "409b1b32-096b-447e-b9a5-53ba46fddcc7"
created_at = "2026-08-16T19:03:53.005506900+00:00"
title = "Add Guidance Lifecycle Agent for repository customizations"
state = "planning"
type = "task"
component = "doc"
