id = "a76c72e6-0bb9-48ef-be43-37c72ad89002"
created_at = "2026-05-21T11:44:36.840290900+00:00"
title = "Project tracker: rule-api hierarchy and documentation pipeline"
state = "planning"
effort = "1200"
type = "tracker-improvement"
component = "doc"
